# Generated by Django 3.0.8 on 2020-07-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('client_member_id', models.BigIntegerField()),
                ('account_id', models.BigIntegerField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
